### ISSUE TITLE
Reload bei "Zurück" / Orientation Wechsel

### ISSUE THREAD

**Issue by lennart-bader** [MyTFG/mytfg-app-android#12]
Ein kompletter Reload bei jeder erneuten Anzeige eines Fragments sollte verhindert werden.

http://stackoverflow.com/questions/28929637/difference-and-uses-of-oncreate-oncreateview-and-
onactivitycreated-in-fra

**Comment by lennart-bader** [comment]
Man könnte hier auch in den jeweiligen Fragmenten statische Variablen für die angezeigten Elemente nehmen und statische Methoden deklarieren, welche die Inhalte ggfs. aktualisieren.

**Comment by Turakar** [comment]
Siehe dazu Parameter Bundle savedInstanceState bei onCreateView() der Fragments. Vielleicht lässt sich da etwas machen.

**Comment by lennart-bader** [comment]
Das ist eigentlich schon veraltet und wird durch die Verwendung von Modulen, die die Fragmente überdauern vermieden.
