### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by rleh** [MyTFG/mytfg-app-android#2]
Für welche Android Version wollen wir entwickeln?

Designmäßig würde ich das _Material Design_ vorschlagen, umgesetzt mit HIlfe der AppCompat Library (idealerweise nur auf Geräten mit Android < 5.0)

Ich denke wir können API Level 15 (Android 4.0.3) vorraussetzen, damit erreichen wir so ~94% der Handys.

**Comment by lennart-bader** [comment]
Ja denke ich auch.
Was ist denn eigentlich unsere Zielgruppe? Alle Nutzer oder nur Admins / Lehrer?
Machen wir dann auch der TFG-App Konkurrenz mit VPlan und so? :smile: 

Dann kriegt der Meyer nen Rappel.

**Comment by rleh** [comment]
Zielgruppe: eindeutig alle Nutzer.

Was für eine TFG App? ;) Diese komische von Appseleration?

Außerdem machen wir der App ja genau genommen keine Konkurrenz, wir besetzen nur die Sparte, die nicht von der alten App abgedeckt wird, nämlich alle Android Versionen > 4.0 :D

Der Meyer soll keinen Rappel kriegen, sondern dankbar sein!

**Comment by lennart-bader** [comment]
Wieso wird das nicht abgedeckt? Also bei mir ist sie drauf :tongue: 

Ok, dann alle Nutzer

**Comment by Harry-R** [comment]
Allein wenn wir einen halbwegs vernünftig designeten VPlan mit push-Benachrichtigungen hinbekommen, ist unserer App besser.
Wenn der Meyer bei der alten App bleiben will, kann er das gerne tun. Die bessere App wird sich schon durchsetzen^^

**Comment by lennart-bader** [comment]
Stimmt. Wobei wir für den VPlan generell noch ein System für die Benachrichtigungen brauchen. Die ganze DB ist ganz anders angelegt, als ich es gedacht hätte, weil das ja zu Meyer kompatibel sein sollte.

**Comment by rleh** [comment]
> Wieso wird das nicht abgedeckt? Also bei mir ist sie drauf :tongue:

Aber nicht auf offiziellem Wege über den Play Store.
Und abstürzen tut die App bestimmt auch regelmäßig ;)
