### ISSUE TITLE
MarkDown Support

### ISSUE THREAD

**Issue by lennart-bader** [MyTFG/mytfg-app-android#24]
MarkDown Support bereitstellen.

**Comment by rleh** [comment]
Mit [dieser](https://github.com/Uncodin/bypass) Library?

**Comment by lennart-bader** [comment]
Ja

**Comment by rleh** [comment]
Die oben genannte Library (https://github.com/Uncodin/bypass) ist inzwischen für Gradle adaptiert worden: https://github.com/Commit451/bypasses
Der Name wurde von _bypass_ in _bypasses_ geändert. :wink: 

Kann einfach als Gradle Dependency eingebunden werden:

```
dependencies {
    compile 'com.commit451:bypasses:1.0.0'
}
```
