### ISSUE TITLE
Zurück-Knopf

### ISSUE THREAD

**Issue by Turakar** [MyTFG/mytfg-app-android#32]
Wenn der Zurück-Knopf oben gedrückt wird und nicht die Hardwaretaste, wird die Slidebar geöffnet und nicht das vorherige Item.

**Comment by lennart-bader** [comment]
Das ist in diesem Sinne kein Bug, sondern einfach ein fehlendes Feature :smile: 

Das müsste in der Navigation implementiert werden, dass da nicht nur das Icon, sondern auch die Funktion geändert werden. Das Event kommt glaube ich in der MainActivity onOptionItemSelect oder so an.

**Comment by lennart-bader** [comment]
Siehe #37
