### ISSUE TITLE
"Login gültig bis"-Anzeige zeigt letzten Login an

### ISSUE THREAD

**Issue by Turakar** [MyTFG/mytfg-app-android#33]
Es wird nicht die Gültigkeitsdauer angezeigt, sondern die Zeit des letzten Logins.

**Comment by rleh** [comment]
Also bei mir wird da definitiv nicht die Zeit des letzten Login angezeigt, sondern das Ablaufdatum.
Meine Version ist vor ein paar Tagen aus _develop_ kompiliert worden, aber am Code fürs Login wurde doch nichts geändert?!

![screenshot](https://cloud.githubusercontent.com/assets/2820734/10210273/02443b86-67e5-11e5-97fe-4312d8c48e36.png)

**Comment by Turakar** [comment]
Du hast Recht, habe mich im Monat vertan.
